
CREATE TABLE YOURAPP.CATEGP ( 
	CATID DECIMAL(5, 0) NOT NULL DEFAULT 0 , 
	CATNAME CHAR(30) CCSID 37 NOT NULL DEFAULT '' , 
	PRIMARY KEY( CATID ) )
	RCDFMT CATEG; 

LABEL ON TABLE YOURAPP.CATEGP 
	IS 'Product Categories' ; 

LABEL ON COLUMN YOURAPP.CATEGP 
( CATID TEXT IS 'Category Id' , 
	CATNAME TEXT IS 'Category Name' ) ; 

GRANT DELETE , INSERT , SELECT , UPDATE
ON YOURAPP.CATEGP TO PUBLIC ; 

INSERT INTO YOURAPP.CATEGP VALUES(101, 'Navigational Systems')