
CREATE TABLE YOURAPP.FEATURESP ( 
	FEID DECIMAL(5, 0) NOT NULL DEFAULT 0 , 
	FENAME CHAR(30) CCSID 37 NOT NULL DEFAULT '' , 
	FEDESC CHAR(60) CCSID 37 NOT NULL DEFAULT '' , 
	PRIMARY KEY( FEID ) )
	RCDFMT FEATURES; 

LABEL ON TABLE YOURAPP.FEATURESP 
	IS 'Features' ; 

LABEL ON COLUMN YOURAPP.FEATURESP 
( FEID TEXT IS 'Feature Id' , 
	FENAME TEXT IS 'Feature Name' , 
	FEDESC TEXT IS 'Description' ) ; 

GRANT DELETE , INSERT , SELECT , UPDATE
ON YOURAPP.FEATURESP TO PUBLIC ; 
