
CREATE TABLE YOURAPP.ORDERS ( 
	ORDERNUM CHAR(7) CCSID 37 NOT NULL DEFAULT '' , 
	STREET1 CHAR(30) CCSID 37 NOT NULL DEFAULT '' , 
	STREET2 CHAR(30) CCSID 37 NOT NULL DEFAULT '' , 
	CITY CHAR(25) CCSID 37 NOT NULL DEFAULT '' , 
	STATE CHAR(2) CCSID 37 NOT NULL DEFAULT '' , 
	ZIP CHAR(5) CCSID 37 NOT NULL DEFAULT '' , 
	ORDERPRID DECIMAL(5, 0) NOT NULL DEFAULT 0 , 
	PRICE DECIMAL(7, 2) NOT NULL DEFAULT 0 , 
	PRIMARY KEY( ORDERNUM ) )
	RCDFMT ORDER; 

LABEL ON COLUMN YOURAPP.ORDERS 
( ORDERNUM TEXT IS 'Order Number' , 
	STREET1 TEXT IS 'Address Line 1' , 
	STREET2 TEXT IS 'Address Line 2' , 
	CITY TEXT IS 'City' , 
	STATE TEXT IS 'City' , 
	ZIP TEXT IS 'Zip' ) ; 

GRANT DELETE , INSERT , SELECT , UPDATE   
ON YOURAPP.ORDERS TO PUBLIC ; 