
CREATE TABLE YOURAPP.PRODFEATP ( 
	XPRID DECIMAL(5, 0) NOT NULL DEFAULT 0 , 
	XFEID DECIMAL(5, 0) NOT NULL DEFAULT 0 , 
	PRIMARY KEY( XPRID , XFEID ) )   
	RCDFMT PRODFEAT   ; 

LABEL ON TABLE YOURAPP.PRODFEATP 
	IS 'Product/Features Cross-Reference' ; 

LABEL ON COLUMN YOURAPP.PRODFEATP 
( XPRID TEXT IS 'Product Id' , 
	XFEID TEXT IS 'Feature Id' ) ; 

GRANT DELETE , INSERT , SELECT , UPDATE   
ON YOURAPP.PRODFEATP TO PUBLIC ; 